---
# run with -K parameter!
- name: Install and configure doas, remove sudo
  hosts: all
  become: true
  tasks:
    - name: Add alias to .bashrc for user
      lineinfile:
        path: ~/.bashrc
        line: "alias sudo='doas'"
        create: true
        state: present
        insertafter: EOF
      become: no

    - name: Install doas
      apt:
        name: doas
        state: latest
      become_method: sudo

    - name: Create /etc/doas.conf
      copy:
        dest: /etc/doas.conf
        content: |
          permit nopass :ubuntu
        owner: root
        group: root
        mode: '0644'
      become_method: sudo

    - name: Remove sudo
      shell:
        cmd: doas su root; export SUDO_FORCE_REMOVE=yes; apt-get remove -y sudo

    - name: Run apt-get autoremove
      apt:
        autoremove: true
      become_method: doas

    - name: Purge all unused packages
      shell:
        cmd: apt-get purge $(dpkg --list | grep '^rc' | awk '{print $2}') -y
      become_method: doas
