---
- name: Install and remove packages based on variables file
  hosts: all
  become: true
  vars_files:
    - vars/packages.yaml
  tasks:
    - name: Install packages
      apt:
        name: "{{ packages }}"
        update_cache: true
        state: present
#
#    - name: Get list of installed packages without "automatic" parameter
#      shell: "apt list --installed | grep -v automatic | cut -f1 -d'/' | cut -f1 -d':'"
#      register: installed_packages
#      changed_when: False
#
#    - name: Convert installed packages to list
#      set_fact:
#        installed_packages_list: "{{ installed_packages.stdout_lines }}"
#
#    - name: Determine which packages to remove
#      set_fact:
#        packages_to_remove: "{{ installed_packages_list | difference(packages) }}"
#
#    - name: Remove packages not in the list
#      apt:
#        name: "{{ packages_to_remove }}"
#        autoremove: true
#        purge: true
#        state: absent
#      when: packages_to_remove | length > 0
