---
all:
  children:
    nodes:
      hosts:
        big-chonker:
          ansible_user: root
          ansible_host: big-chonker.rapid.internal
          lo_ip: 192.168.71.6

        lanberg:
          ansible_user: root
          ansible_host: lanberg.rapid.internal
          lo_ip: 192.168.71.7

#        cyborg:
#          ansible_user: root
#          ansible_host: cyborg.rapid.internal
#          lo_ip: 192.168.71.8

    master:
      hosts:
        big-chonker:
