- name: Configure Rocky Linux and install oVirt
  hosts: all
  become: true
  vars:
    timezone: "Europe/Warsaw"
    ntp_servers:
      - "192.168.14.1"
      - "time.cloudflare.com"
      - "time.aws.com"

  tasks:
    - name: Stop firewalld
      ansible.builtin.service:
        name: firewalld
        state: stopped

    - name: Disable firewalld from starting at boot
      ansible.builtin.systemd:
        name: firewalld
        enabled: no
        state: stopped

    - name: Load FRR interface variables
      include_vars:
        file: "vars/frr_interfaces.yaml"
        name: frr_interfaces

    - name: Set timezone to Europe/Warsaw
      ansible.builtin.command: timedatectl set-timezone {{ timezone }}

    - name: Ensure chronyd is installed and enabled
      ansible.builtin.dnf:
        name: chrony
        state: present
      notify: restart chronyd

    - name: Configure NTP servers in chrony.conf
      lineinfile:
        path: /etc/chrony.conf
        line: "server {{ item }} iburst"
        state: present
      loop: "{{ ntp_servers }}"
      notify: restart chronyd

    - name: Add entries to /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ frr_interfaces[inventory_hostname]['lo_ip'] }} {{ inventory_hostname }}.ovirt.internal {{ inventory_hostname }}"
        state: present

    - name: Install dnf plugins core
      ansible.builtin.dnf:
        name: dnf-plugins-core
        state: present

    - name: Enable the oVirt COPR repository
      ansible.builtin.command: dnf copr enable -y ovirt/ovirt-master-snapshot centos-stream-9

    - name: Install ovirt-release-master
      ansible.builtin.dnf:
        name: ovirt-release-master
        state: present

    - name: Install oVirt packages
      ansible.builtin.dnf:
        name:
          - centos-release-ovirt45
          - ovirt-openvswitch
          - https://kojihub.stream.centos.org/kojifiles/packages/nmstate/2.0.0/2.el9/noarch/nmstate-plugin-ovsdb-2.0.0-2.el9.noarch.rpm
          - https://kojihub.stream.centos.org/kojifiles/packages/nmstate/2.0.0/2.el9/noarch/python3-libnmstate-2.0.0-2.el9.noarch.rpm
        state: present
        disable_gpg_check: true

    - name: Synchronize DNF packages
      ansible.builtin.dnf:
        name: '*'
        state: latest
        update_cache: yes
        skip_broken: yes

    - name: Set stream version for yum
      ansible.builtin.copy:
        dest: /etc/yum/vars/stream
        content: "9-stream"

  handlers:
    - name: restart chronyd
      ansible.builtin.systemd:
        name: chronyd
        state: restarted
