---
- name: Update and upgrade all packages
  hosts: all
  become: true
  tasks:
    - name: Update apt package list
      apt:
        update_cache: true

    - name: Upgrade all apt packages
      apt:
        upgrade: safe

    - name: Run apt-get autoremove
      apt:
        autoremove: true
